baseURL: https://www.partingsong.org
languageCode: zh-CN
defaultContentLanguage: zh-cn
defaultContentLanguageInSubdir: true
title: 骊歌
copyright: "© 2026 Zhixiao Zhang"
theme: "hugo-xmag"

pagination:
  pagerSize: 6

enableInlineShortcodes: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
footnotereturnlinkcontents: "↩"
hasCJKLanguage: true

languages:
  zh-cn:
    menu:
      main:
        - name: 首页
          url: /
          weight: 1
        - name: 分类
          url: /categories/
          weight: 2
        - name: 个人简介
          url: /about/
          weight: 3
        - name: 歌词
          url: /lyrics/
          weight: 4
    contentDir: content/zh-cn

  en:
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: Categories
          url: /categories/
          weight: 2
        - name: About
          url: /about/
          weight: 3
    contentDir: content/en
params:
  description: "骊歌 —— 一份关于随笔、读书笔记与粤语歌词的私人杂志,记录思考、生活与心绪流转。"
  subtitle: "PARTINGSONG · A JOURNAL"
  footer: "&copy; Zhixiao Zhang 2024 - 2026 | [Github](https://github.com/zhixiao-zhang)"
  text:
    truncated: "&hellip;"
  summary_length: 200
  terms_exclude:
    - "歌词"
